import { getClient } from "@/db";

let vendasOk = false;
let itensOk = false;
let indexesOk = false;
let vendedoresOk = false;
let unikOk = false;

async function colunasTabela(table: string): Promise<Set<string>> {
  const client = getClient();
  const info = await client.execute({
    sql: `SELECT column_name AS name
          FROM information_schema.columns
          WHERE table_schema = 'public' AND table_name = ?
          ORDER BY ordinal_position`,
    args: [table],
  });
  return new Set((info.rows || []).map((r) => String(r.name || "")));
}

/** Índices para acelerar consultas — não altera/apaga dados. */
export async function ensurePerfIndexes() {
  if (indexesOk) return;
  const client = getClient();
  const stmts = [
    "CREATE INDEX IF NOT EXISTS idx_itens_ativo ON itens(ativo)",
    "CREATE INDEX IF NOT EXISTS idx_itens_subcategoria ON itens(subcategoria_meep)",
    "CREATE INDEX IF NOT EXISTS idx_estoque_unidade ON estoque(unidade)",
    "CREATE INDEX IF NOT EXISTS idx_estoque_sku ON estoque(sku)",
    "CREATE INDEX IF NOT EXISTS idx_vendas_data ON vendas(data)",
    "CREATE INDEX IF NOT EXISTS idx_vendas_sku ON vendas(sku)",
    "CREATE INDEX IF NOT EXISTS idx_vendas_unidade ON vendas(unidade)",
    "CREATE INDEX IF NOT EXISTS idx_vendas_vendedor ON vendas(vendedor)",
    "CREATE INDEX IF NOT EXISTS idx_vendas_status ON vendas(status)",
    "CREATE INDEX IF NOT EXISTS idx_log_data ON log_operacoes(data_hora)",
    "CREATE INDEX IF NOT EXISTS idx_log_tipo ON log_operacoes(tipo)",
    "CREATE INDEX IF NOT EXISTS idx_prime_data ON prime_vendas(data)",
    "CREATE INDEX IF NOT EXISTS idx_mov_estoque ON movimentos_estoque(sku, unidade)",
    "CREATE INDEX IF NOT EXISTS idx_entrega_unik_data ON entrega_unik(data)",
    "CREATE INDEX IF NOT EXISTS idx_entrega_unik_sku ON entrega_unik(sku)",
  ];
  for (const sql of stmts) {
    try {
      await client.execute(sql);
    } catch {
      /* índice já existe ou tabela ainda não criada */
    }
  }
  indexesOk = true;
}

export async function ensureVendasSchema() {
  if (vendasOk) return;
  const client = getClient();
  await client.execute(`
    CREATE TABLE IF NOT EXISTS vendas (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      data TEXT NOT NULL,
      id_vendedor TEXT,
      vendedor TEXT,
      unidade TEXT NOT NULL,
      categoria TEXT,
      subcategoria TEXT,
      sku TEXT NOT NULL,
      descricao TEXT,
      preco_unitario DOUBLE PRECISION NOT NULL DEFAULT 0,
      quantidade INTEGER NOT NULL DEFAULT 1,
      subtotal_bruto DOUBLE PRECISION NOT NULL DEFAULT 0,
      desconto DOUBLE PRECISION NOT NULL DEFAULT 0,
      valor_recebido DOUBLE PRECISION NOT NULL DEFAULT 0,
      status TEXT DEFAULT '',
      cancelado_por TEXT,
      cancelado_em TEXT,
      motivo_cancelamento TEXT
    )
  `);
  const cols = await colunasTabela("vendas");
  if (!cols.has("motivo_cancelamento")) {
    await client.execute("ALTER TABLE vendas ADD COLUMN motivo_cancelamento TEXT");
  }
  vendasOk = true;
  void ensurePerfIndexes();
  void import("./materialized-views").then((m) => m.ensureVendasMensalMV()).catch(() => {});
}

export async function ensureItensSchema() {
  if (itensOk) return;
  const client = getClient();
  await client.execute(`
    CREATE TABLE IF NOT EXISTS itens (
      sku TEXT PRIMARY KEY,
      categoria_dash TEXT,
      subcategoria_meep TEXT,
      descricao TEXT NOT NULL,
      preco DOUBLE PRECISION NOT NULL DEFAULT 0,
      ativo BOOLEAN NOT NULL DEFAULT TRUE,
      custo DOUBLE PRECISION NOT NULL DEFAULT 0,
      foto_url TEXT,
      ilimitado BOOLEAN NOT NULL DEFAULT FALSE,
      sugestao_venda DOUBLE PRECISION NOT NULL DEFAULT 0
    )
  `);
  const cols = await colunasTabela("itens");
  if (!cols.has("ilimitado")) {
    await client.execute("ALTER TABLE itens ADD COLUMN ilimitado BOOLEAN NOT NULL DEFAULT FALSE");
  }
  if (!cols.has("preco_final_salvo")) {
    await client.execute(
      "ALTER TABLE itens ADD COLUMN preco_final_salvo BOOLEAN NOT NULL DEFAULT FALSE"
    );
  }
  if (!cols.has("sugestao_venda")) {
    await client.execute(
      "ALTER TABLE itens ADD COLUMN sugestao_venda DOUBLE PRECISION NOT NULL DEFAULT 0"
    );
  }
  if (!cols.has("unidades")) {
    await client.execute("ALTER TABLE itens ADD COLUMN unidades TEXT NOT NULL DEFAULT '[]'");
  }
  itensOk = true;
}

let primeOk = false;

export async function ensurePrimeSchema() {
  if (primeOk) return;
  const client = getClient();
  await client.execute(`
    CREATE TABLE IF NOT EXISTS prime_vendas (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      data TEXT NOT NULL,
      id_vendedor TEXT,
      vendedor TEXT,
      unidade TEXT,
      item TEXT NOT NULL,
      quantidade INTEGER NOT NULL DEFAULT 1,
      valor DOUBLE PRECISION NOT NULL DEFAULT 0,
      nivel TEXT,
      status TEXT DEFAULT '',
      cancelado_por TEXT,
      cancelado_em TEXT,
      motivo_cancelamento TEXT
    )
  `);
  const cols = await colunasTabela("prime_vendas");
  if (!cols.has("status")) {
    await client.execute("ALTER TABLE prime_vendas ADD COLUMN status TEXT DEFAULT ''");
  }
  if (!cols.has("cancelado_por")) {
    await client.execute("ALTER TABLE prime_vendas ADD COLUMN cancelado_por TEXT");
  }
  if (!cols.has("cancelado_em")) {
    await client.execute("ALTER TABLE prime_vendas ADD COLUMN cancelado_em TEXT");
  }
  if (!cols.has("motivo_cancelamento")) {
    await client.execute("ALTER TABLE prime_vendas ADD COLUMN motivo_cancelamento TEXT");
  }
  primeOk = true;
  void ensurePerfIndexes();
}

export async function ensureVendedoresSchema() {
  if (vendedoresOk) return;
  const client = getClient();
  await client.execute(`
    CREATE TABLE IF NOT EXISTS vendedores (
      id TEXT PRIMARY KEY,
      nome TEXT NOT NULL,
      ativo BOOLEAN NOT NULL DEFAULT TRUE,
      unidades TEXT NOT NULL DEFAULT '[]'
    )
  `);
  const cols = await colunasTabela("vendedores");
  if (!cols.has("unidades")) {
    await client.execute("ALTER TABLE vendedores ADD COLUMN unidades TEXT NOT NULL DEFAULT '[]'");
  }
  vendedoresOk = true;
}

export async function ensureUnikSchema() {
  if (unikOk) return;
  await ensureItensSchema();
  const client = getClient();
  await client.execute(`
    CREATE TABLE IF NOT EXISTS entrega_unik (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      data TEXT,
      tipo TEXT,
      nome TEXT,
      sku TEXT,
      quantidade DOUBLE PRECISION DEFAULT 0,
      status TEXT,
      unidade TEXT,
      estoque_aplicado BOOLEAN NOT NULL DEFAULT FALSE,
      foto_url TEXT,
      custo DOUBLE PRECISION NOT NULL DEFAULT 0,
      sugestao_venda DOUBLE PRECISION NOT NULL DEFAULT 0,
      recebido_por TEXT,
      estoque_unidade TEXT
    )
  `);
  await client.execute(`
    CREATE TABLE IF NOT EXISTS unik_vinculos (
      nome_chave TEXT PRIMARY KEY,
      sku TEXT NOT NULL,
      nome_original TEXT
    )
  `);
  const cols = await colunasTabela("entrega_unik");
  if (!cols.has("estoque_aplicado")) {
    await client.execute(
      "ALTER TABLE entrega_unik ADD COLUMN estoque_aplicado BOOLEAN NOT NULL DEFAULT FALSE"
    );
  }
  if (!cols.has("foto_url")) {
    await client.execute("ALTER TABLE entrega_unik ADD COLUMN foto_url TEXT");
  }
  if (!cols.has("custo")) {
    await client.execute("ALTER TABLE entrega_unik ADD COLUMN custo DOUBLE PRECISION NOT NULL DEFAULT 0");
  }
  if (!cols.has("sugestao_venda")) {
    await client.execute(
      "ALTER TABLE entrega_unik ADD COLUMN sugestao_venda DOUBLE PRECISION NOT NULL DEFAULT 0"
    );
  }
  if (!cols.has("recebido_por")) {
    await client.execute("ALTER TABLE entrega_unik ADD COLUMN recebido_por TEXT");
  }
  if (!cols.has("estoque_unidade")) {
    await client.execute("ALTER TABLE entrega_unik ADD COLUMN estoque_unidade TEXT");
  }
  await client.execute(`
    CREATE TABLE IF NOT EXISTS unik_loja_status (
      sku TEXT NOT NULL,
      unidade TEXT NOT NULL,
      enviado BOOLEAN NOT NULL DEFAULT FALSE,
      lancado BOOLEAN NOT NULL DEFAULT FALSE,
      PRIMARY KEY (sku, unidade)
    )
  `);
  await client.execute("CREATE INDEX IF NOT EXISTS idx_entrega_unik_data ON entrega_unik(data)");
  await client.execute("CREATE INDEX IF NOT EXISTS idx_entrega_unik_sku ON entrega_unik(sku)");
  unikOk = true;
}
