import { getClient } from "@/db";
import { hashSenha } from "./password";

let pronto = false;

export async function ensureUsuariosTable() {
  if (pronto) return;
  const client = getClient();

  await client.execute(`
    CREATE TABLE IF NOT EXISTS usuarios (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      login TEXT NOT NULL UNIQUE,
      nome TEXT NOT NULL,
      senha_hash TEXT NOT NULL,
      paginas TEXT NOT NULL DEFAULT '[]',
      ativo BOOLEAN NOT NULL DEFAULT TRUE,
      sessao_ver INTEGER NOT NULL DEFAULT 1
    )
  `);

  const cols = await client.execute({
    sql: `SELECT column_name FROM information_schema.columns
          WHERE table_schema = 'public' AND table_name = 'usuarios'`,
    args: [],
  });
  const colSet = new Set((cols.rows || []).map((r) => String(r.column_name)));
  if (!colSet.has("sessao_ver")) {
    await client.execute(
      "ALTER TABLE usuarios ADD COLUMN sessao_ver INTEGER NOT NULL DEFAULT 1"
    );
  }
  if (!colSet.has("unidades")) {
    await client.execute(
      "ALTER TABLE usuarios ADD COLUMN unidades TEXT NOT NULL DEFAULT '[]'"
    );
  }

  const count = await client.execute("SELECT COUNT(*) AS c FROM usuarios");
  const qtd = Number(count.rows?.[0]?.c ?? 0);
  if (qtd === 0) {
    const senha = process.env.ADMIN_SENHA_INICIAL || "admin123";
    await client.execute({
      sql: "INSERT INTO usuarios (login, nome, senha_hash, paginas, ativo) VALUES (?, ?, ?, ?, TRUE)",
      args: ["admin", "Administrador", hashSenha(senha), "*"],
    });
  } else {
    await client.execute(
      "UPDATE usuarios SET login = 'admin', paginas = '*' WHERE login IN ('admin', 'admin@60minutos.local')"
    );
  }

  pronto = true;
}
