/**
 * Cria o schema PostgreSQL completo e índices.
 * Uso: npx tsx src/db/migrate.ts
 */
import { client } from "./index";
import { loadEnvLocal } from "../lib/load-env";
import { hashSenha } from "../lib/password";

loadEnvLocal();

const SQL = `
CREATE TABLE IF NOT EXISTS vendedores (
  id TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  unidades TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS itens (
  sku TEXT PRIMARY KEY,
  categoria_dash TEXT,
  subcategoria_meep TEXT,
  descricao TEXT NOT NULL,
  preco DOUBLE PRECISION NOT NULL DEFAULT 0,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  custo DOUBLE PRECISION NOT NULL DEFAULT 0,
  foto_url TEXT,
  ilimitado BOOLEAN NOT NULL DEFAULT FALSE,
  sugestao_venda DOUBLE PRECISION NOT NULL DEFAULT 0,
  preco_final_salvo BOOLEAN NOT NULL DEFAULT FALSE,
  unidades TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE IF NOT EXISTS estoque (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL REFERENCES itens(sku),
  unidade TEXT NOT NULL,
  quantidade INTEGER NOT NULL DEFAULT 0,
  nome TEXT,
  UNIQUE(sku, unidade)
);

CREATE TABLE IF NOT EXISTS vendas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data TEXT NOT NULL,
  id_vendedor TEXT,
  vendedor TEXT,
  unidade TEXT NOT NULL,
  categoria TEXT,
  subcategoria TEXT,
  sku TEXT NOT NULL,
  descricao TEXT,
  preco_unitario DOUBLE PRECISION NOT NULL DEFAULT 0,
  quantidade INTEGER NOT NULL DEFAULT 1,
  subtotal_bruto DOUBLE PRECISION NOT NULL DEFAULT 0,
  desconto DOUBLE PRECISION NOT NULL DEFAULT 0,
  valor_recebido DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT DEFAULT '',
  cancelado_por TEXT,
  cancelado_em TEXT,
  motivo_cancelamento TEXT
);

CREATE TABLE IF NOT EXISTS prime_vendas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data TEXT NOT NULL,
  id_vendedor TEXT,
  vendedor TEXT,
  unidade TEXT,
  item TEXT NOT NULL,
  quantidade INTEGER NOT NULL DEFAULT 1,
  valor DOUBLE PRECISION NOT NULL DEFAULT 0,
  nivel TEXT,
  status TEXT DEFAULT '',
  cancelado_por TEXT,
  cancelado_em TEXT,
  motivo_cancelamento TEXT
);

CREATE TABLE IF NOT EXISTS log_operacoes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_hora TEXT NOT NULL,
  operador TEXT,
  tipo TEXT NOT NULL,
  sucesso BOOLEAN NOT NULL DEFAULT TRUE,
  dados TEXT,
  mensagem TEXT
);

CREATE TABLE IF NOT EXISTS entrega_unik (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data TEXT,
  tipo TEXT,
  nome TEXT,
  sku TEXT,
  quantidade DOUBLE PRECISION DEFAULT 0,
  status TEXT,
  unidade TEXT,
  estoque_aplicado BOOLEAN NOT NULL DEFAULT FALSE,
  foto_url TEXT,
  custo DOUBLE PRECISION NOT NULL DEFAULT 0,
  sugestao_venda DOUBLE PRECISION NOT NULL DEFAULT 0,
  recebido_por TEXT,
  estoque_unidade TEXT
);

CREATE TABLE IF NOT EXISTS unik_vinculos (
  nome_chave TEXT PRIMARY KEY,
  sku TEXT NOT NULL,
  nome_original TEXT
);

CREATE TABLE IF NOT EXISTS unik_loja_status (
  sku TEXT NOT NULL,
  unidade TEXT NOT NULL,
  enviado BOOLEAN NOT NULL DEFAULT FALSE,
  lancado BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (sku, unidade)
);

CREATE TABLE IF NOT EXISTS movimentos_estoque (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_hora TEXT NOT NULL,
  sku TEXT NOT NULL,
  unidade TEXT NOT NULL,
  delta INTEGER NOT NULL,
  quantidade_apos INTEGER,
  tipo TEXT NOT NULL,
  operador TEXT,
  referencia TEXT
);

CREATE TABLE IF NOT EXISTS estoque_snapshots (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes TEXT NOT NULL,
  sku TEXT NOT NULL,
  unidade TEXT NOT NULL,
  quantidade INTEGER NOT NULL DEFAULT 0,
  UNIQUE(mes, sku, unidade)
);

CREATE INDEX IF NOT EXISTS idx_entrega_unik_data ON entrega_unik(data);
CREATE INDEX IF NOT EXISTS idx_entrega_unik_sku ON entrega_unik(sku);
CREATE INDEX IF NOT EXISTS idx_vendas_data ON vendas(data);
CREATE INDEX IF NOT EXISTS idx_vendas_sku ON vendas(sku);
CREATE INDEX IF NOT EXISTS idx_vendas_unidade ON vendas(unidade);
CREATE INDEX IF NOT EXISTS idx_log_data ON log_operacoes(data_hora);
CREATE INDEX IF NOT EXISTS idx_mov_estoque ON movimentos_estoque(sku, unidade);

CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  nome TEXT NOT NULL,
  senha_hash TEXT NOT NULL,
  paginas TEXT NOT NULL DEFAULT '[]',
  unidades TEXT NOT NULL DEFAULT '[]',
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  sessao_ver INTEGER NOT NULL DEFAULT 1
);
`;

async function migrate() {
  const statements = SQL.split(";")
    .map((s) => s.trim())
    .filter(Boolean);
  for (const stmt of statements) {
    await client.execute(stmt);
  }

  const count = await client.execute("SELECT COUNT(*) AS c FROM usuarios");
  const qtd = Number(count.rows?.[0]?.c ?? 0);
  if (qtd === 0) {
    const senha = process.env.ADMIN_SENHA_INICIAL || "admin123";
    await client.execute({
      sql: "INSERT INTO usuarios (login, nome, senha_hash, paginas, ativo) VALUES (?, ?, ?, ?, TRUE)",
      args: ["admin", "Administrador", hashSenha(senha), "*"],
    });
    console.log("Admin criado: admin /", senha);
  }

  console.log("Migração PostgreSQL OK");
}

migrate().catch((e) => {
  console.error(e);
  process.exit(1);
});
